version: "3.8"

services:
  postgres:
    container_name: hospital-postgres
    image: postgres:13-alpine
    volumes:
      - $PWD/docker/postgres-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: hospital
    ports:
      - 5433:5432
