version: "3.8"

services:
  as-postgres:
    image: postgres:9-alpine
    volumes:
      - $PWD/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: hospital
